#!/bin/bash
set -e

# Requirements:
#
# sudo yum install --assumeyes rpm-build yum-utils epel-release

if ! rpm --query centos-release > /dev/null && ! rpm --query redhat-release > /dev/null; then
	echo 'Can only be run in CentOS or RHEL'
	exit 1
fi

SPEC=${1:-*}

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR="$HERE"
ESCAPED_TOPDIR=$(printf %q "$TOPDIR")

sudo yum-builddep --assumeyes "$TOPDIR/SPECS/"$SPEC.spec

rpmbuild -bb --define "_topdir $ESCAPED_TOPDIR" "$TOPDIR/SPECS/"$SPEC.spec --noclean \
	2>&1 | tee "$HERE/build-rpms.log"
