#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")
ESCAPED_HERE=$(printf %q "$HERE")
BUILDROOT="$HERE/../BUILDROOT"

sudo yum install --assumeyes rpm-build
sudo yum-builddep --assumeyes SPECS/*.spec
mkdir --parents "$BUILDROOT"
rpmbuild --define "_topdir $ESCAPED_HERE" --buildroot="$BUILDROOT" -ba SPECS/*.spec
