#!/bin/bash
set -e

SPEC=${1:-*}

HERE=$(dirname "$(readlink -f "$0")")
ESCAPED_TOPDIR=$(printf %q "$HERE")

sudo yum install --assumeyes rpm-build epel-release
sudo yum-builddep --assumeyes SPECS/*.spec

rpmbuild --define "_topdir $ESCAPED_TOPDIR" --short-circuit -bi "$TOPDIR/SPECS/"$SPEC.spec \
	2>&1 | tee "$HERE/build.log" 
