#
# Phase 1: Provisioning
#

- hosts: localhost
  gather_facts: false
  tasks:

  # Configuration
  - name: Configure OpenStack
    os_client_config:

  - name: Import topology.yaml
    include_vars:
      name: topology
      file: topology.yaml

  - include_role:
      name: openstack-keypair

  - include_role:
      name: openstack-servers

#
# Phase 2: Configuration
#

- hosts: clearwater
  gather_facts: false
  tasks:

  - name: Wait for servers to become available
    command: /bin/true

  - include_role:
      name: essentials

  - include_role:
      name: hosts

  - include_role:
      name: dnsmasq

  - include_role:
      name: clearwater-configuration

#
# Phase 3: Installation
#

  - include_role:
      name: clearwater-repository
  - include_role:
      name: cassandra-repository

  - name: Install Clearwater Infrastructure
    yum:
      name: clearwater-infrastructure
      state: present
      update_cache: true

  - name: Install Clearwater Node
    yum:
      name: clearwater-node-{{ hostvars[inventory_hostname].server.metadata['clearwater.type'] }}
      state: present
      update_cache: true
