#!/bin/bash
set -e

HERE=$(dirname "$(readlink -f "$0")")

nodes:

1. vellum (cassandra storage + memcached with astaire/rogers)
2. chronos (timer)
3. smtp
4. bono (sip edge proxy)
5. sprout (sip router)
6. homestead (hss cache)
7. ralf (ctf)
8. homer (xdms)
9. ellis (provisioning on mysql)

all of them have:

infrastructure (configuration scripts)
monit (monitors and restarts services)
etcd (cluster manager, at least 3 nodes must be masters, first node must be master)

phase 1: provision

provision all VMs, get their public IP address and append to a file

phase 2: configure

on each VM:

update hostname: sprout-<site name>-<zone>
update /etc/hosts
create /etc/clearwater/local_config
create /etc/clearwater/shared_config

phase 3: install

on each VM:

install RPMs
