
- name: Gather packages
  delegate_to: localhost
  shell: >
    mkdir --parents "{{ playbook_dir }}/roles/clearwater-repository/files/clearwater-repository/" &&
    rsync "{{ playbook_dir }}/../../RPMS/x86_64/"*.rpm "{{ playbook_dir }}/roles/clearwater-repository/files/clearwater-repository/"

- name: Check if package repository exists
  register: clearwater_repository
  stat:
    path: /opt/clearwater-repository

- name: Create package repository
  when: not clearwater_repository.stat.exists
  block:

  - copy:
      src: clearwater-repository/
      dest: /opt/clearwater-repository

  - yum:
      name: createrepo
      state: present

  - command: createrepo /opt/clearwater-repository

  - yum_repository:
      name: Clearwater-Local
      description: Clearwater Local
      baseurl: file:///opt/clearwater-repository/
      gpgcheck: false
