#!/bin/bash
set -e

# Requirements:
#
# sudo yum install --assumeyes rpm-build

SPEC=${1:-*}

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR="$HERE/.."
ESCAPED_TOPDIR=$(printf %q "$TOPDIR")
SPECS="$TOPDIR/SPECS"
LOGS="$TOPDIR/logs"

rpmbuild -bs --define "_topdir $ESCAPED_TOPDIR" "$SPECS/"$SPEC.spec \
	2>&1 | tee "$LOGS/build-srpms.log"
