#!/bin/bash
set -e

# Requirements:
#
# sudo dnf install --assumeyes git

VERSION=129

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR="$HERE/.."
SOURCES="$TOPDIR/SOURCES"
WORK=/tmp/clearwater-rpm

function fetch()
{
	local NAME=$1
	local REPO_NAME=${2:-$NAME}
	local ARCHIVE="$SOURCES/$NAME-$VERSION.tar.bz2"
	if [ ! -f  "$ARCHIVE" ]; then
		local REPO="$NAME-$VERSION"
		if [ ! -d "$REPO" ]; then
			mkdir --parents "$WORK"
			git config --global 'url.https://github.com/.insteadOf' 'git@github.com:'
			git clone --depth 1 --recursive --branch "release-$VERSION" "git@github.com:Metaswitch/$REPO_NAME.git" "$WORK/$REPO"
			git config --global --unset 'url.https://github.com/.insteadOf'
		fi
		mkdir --parents "$SOURCES"
		tar --create --bzip2 --exclude-vcs --file="$ARCHIVE" --directory="$WORK" "$REPO"
		rm --recursive --force "$WORK" 
	fi
}

fetch clearwater-crest crest
fetch clearwater-ellis ellis
fetch clearwater-homestead homestead
fetch clearwater-infrastructure
fetch clearwater-logging
fetch clearwater-monit
fetch clearwater-ralf ralf
fetch clearwater-sprout sprout
