#!/bin/bash
set -e

# Requirements:
#
# sudo dnf install --assumeyes mock dnf-utils
# sudo usermod -a -G mock $USER
#
# See: /etc/mock/ for available roots

SPEC=${1:-*}
VERSION=129
MOCK=epel-7-x86_64

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR="$HERE/.."
ESCAPED_TOPDIR=$(printf %q "$TOPDIR")
SPECS="$TOPDIR/SPECS"
SOURCES="$TOPDIR/SOURCES"
SRPMS="$TOPDIR/SRPMS"
RPMS="$TOPDIR/RPMS/x86_64"
LOGS="$TOPDIR/logs"

mock --buildsrpm --root="$MOCK" --sources="$SOURCES" --resultdir="$SRPMS" --spec="$SPECS/"$SPEC.spec \
	2>&1 | tee "$LOGS/mock-build-rpms.log"

mock --rebuild --enable-network --root="$MOCK" --resultdir="$RPMS" "$SRPMS/"$SPEC-*.src.rpm \
	2>&1 | tee "$LOGS/mock-build-rpms.log"

# Rebuild annoyingly also produces SRPMs
rm --force "$RPMS/"*.src.rpm

echo "See: \"$SRPMS/build.log\""
echo "And: \"$RPMS/build.log\""
