#!/bin/bash
set -e

# Requirements:
#
# sudo dnf install --assumeyes mock dnf-utils
# sudo usermod -a -G mock $USER
#
# See: /etc/mock/ for available roots

SPEC=${1:-*}
VERSION=129
MOCK=epel-7-x86_64

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR=$(readlink -f "$HERE/..")
ESCAPED_TOPDIR=$(printf %q "$TOPDIR")
SPECS="$TOPDIR/SPECS"
SOURCES="$TOPDIR/SOURCES"
SRPMS="$TOPDIR/SRPMS"
RPMS="$TOPDIR/RPMS/x86_64"
LOGS="$TOPDIR/logs"

# Build RPMs for target platform from SRPMs (e.g. ".el7.centos.x86_64.rpm")
mock --rebuild --no-cleanup-after --enable-network --root="$MOCK" --resultdir="$RPMS" "$SRPMS/"$SPEC-$VERSION-*.src.rpm \
	2>&1 | tee "$LOGS/mock-build-rpms.log"

# Rebuild produces SRPMs, but we already have them (they were are input!)
rm --force "$RPMS/"*.src.rpm

echo "See: \"$SRPMS/build.log\""
echo "And: \"$RPMS/build.log\""
