#!/bin/bash
set -e

# Requirements:
#
# sudo dnf install --assumeyes mock dnf-utils rpm-build
# sudo usermod -a -G mock $USER
#
# See: /etc/mock/ for available configs

SPEC=${1:-*}
VERSION=129
MOCK=epel-7-x86_64

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR="$HERE/.."
ESCAPED_TOPDIR=$(printf %q "$TOPDIR")
LOGS="$TOPDIR/logs"

rpmbuild -bs --define "_topdir $ESCAPED_TOPDIR" "$TOPDIR/SPECS/"$SPEC.spec \
	2>&1 | tee "$LOGS/mock-build-rpms.log"

mock --root="$MOCK" --resultdir="$TOPDIR/RPMS/%(target_arch)s" --enable-network \
rebuild "$TOPDIR/SRPMS/"$SPEC-$VERSION-* \
	2>&1 | tee "$LOGS/mock-build-rpms.log"

echo "Details in \"$TOPDIR/RPMS/x86_64/build.log\""
