#!/bin/bash
set -e

# Requirements:
#
# sudo yum install --assumeyes rpm-build

if ! rpm --query centos-release > /dev/null && ! rpm --query redhat-release > /dev/null; then
	echo 'Can only be run in CentOS or RHEL'
	exit 1
fi

SPEC=${1:-*}

HERE=$(dirname "$(readlink -f "$0")")
TOPDIR="$HERE/.."
ESCAPED_TOPDIR=$(printf %q "$TOPDIR")
LOGS="$TOPDIR/logs"

rpmbuild -bi --short-circuit --define "_topdir $ESCAPED_TOPDIR" "$TOPDIR/SPECS/"$SPEC.spec \
	2>&1 | tee "$LOGS/validate-install.log" 
