
- name: Install Cassandra repository
  block:

  - yum_repository:
      name: Cassandra
      description: Apache Cassandra
      baseurl: https://www.apache.org/dist/cassandra/redhat/{{ cassandra_version }}/
      gpgcheck: true
      repo_gpgcheck: true
      gpgkey: https://www.apache.org/dist/cassandra/KEYS

  # The following should not be necessary anymore in Ansible 2.6
  # See: https://github.com/ansible/ansible/pull/35989
  - command: yum -y makecache
