
- name: Provision servers
  async: 300 # max 5 minutes
  poll: 0
  register: servers_async
  with_items: "{{ topology.servers }}"
  os_server:
    state: present
    name: "{{ item.type }}-{{ item.index }}.{{ topology.site_name }}.{{ topology.zone }}"
    image: "{{ topology.image }}"
    flavor: "{{ item.flavor }}"
    key_name: "{{ keypair.key.name }}"
    #network: public # not currently supported in Rackspace
    meta:
      clearwater.zone: "{{ topology.zone }}"
      clearwater.site_name: "{{ topology.site_name }}"
      clearwater.type: "{{ item.type }}"
      clearwater.index: "{{ item.index }}"

- name: Wait for servers to become active
  retries: 300 # delay is 5 seconds
  register: servers
  until: servers.finished
  with_items: "{{ servers_async.results }}"
  async_status:
    jid: "{{ item.ansible_job_id }}"

- name: Add servers to group
  with_items: "{{ servers.results }}"
  add_host:
    name: "{{ item.server.name }}"
    groups: clearwater
    # Custom attribute:
    server: "{{ item.server }}"
    # Ansible attributes:
    ansible_ssh_host: "{{ item.server.public_v4 }}"
    ansible_ssh_user: root
    ansible_ssh_private_key_file: "{{ playbook_dir }}/keys/{{ keypair.key.name }}"
